package com.unonomercy.core.ui.theme

import androidx.compose.ui.graphics.Color

// light colors
val primaryLight = Color(0xFF9B0003)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD82219)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFFA8382C)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFF8979)
val onSecondaryContainerLight = Color(0xFF4A0001)
val tertiaryLight = Color(0xFF694500)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF966713)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F7)
val onBackgroundLight = Color(0xFF281715)
val surfaceLight = Color(0xFFFFF8F7)
val onSurfaceLight = Color(0xFF281715)
val surfaceVariantLight = Color(0xFFFFDAD5)
val onSurfaceVariantLight = Color(0xFF5D3F3B)
val outlineLight = Color(0xFF916F6A)
val outlineVariantLight = Color(0xFFE6BDB7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF3F2C29)
val inverseOnSurfaceLight = Color(0xFFFFEDEA)
val inversePrimaryLight = Color(0xFFFFB4A9)
val surfaceDimLight = Color(0xFFF3D3CE)
val surfaceBrightLight = Color(0xFFFFF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0EE)
val surfaceContainerLight = Color(0xFFFFE9E6)
val surfaceContainerHighLight = Color(0xFFFFE2DD)
val surfaceContainerHighestLight = Color(0xFFFCDBD6)

// dark colors
val primaryDark = Color(0xFFFFB4A9)
val onPrimaryDark = Color(0xFF561E17)
val primaryContainerDark = Color(0xFF73342B)
val onPrimaryContainerDark = Color(0xFFFFDAD5)
val secondaryDark = Color(0xFFE7BDB7)
val onSecondaryDark = Color(0xFF442926)
val secondaryContainerDark = Color(0xFF5D3F3B)
val onSecondaryContainerDark = Color(0xFFFFDAD5)
val tertiaryDark = Color(0xFFDEC38C)
val onTertiaryDark = Color(0xFF3E2E04)
val tertiaryContainerDark = Color(0xFF574419)
val onTertiaryContainerDark = Color(0xFFFCDFA6)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A1110)
val onBackgroundDark = Color(0xFFF1DEDC)
val surfaceDark = Color(0xFF1A1110)
val onSurfaceDark = Color(0xFFF1DEDC)
val surfaceVariantDark = Color(0xFF534341)
val onSurfaceVariantDark = Color(0xFFD8C2BE)
val outlineDark = Color(0xFFA08C89)
val outlineVariantDark = Color(0xFF534341)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF1DEDC)
val inverseOnSurfaceDark = Color(0xFF392E2C)
val inversePrimaryDark = Color(0xFF904A41)
val surfaceDimDark = Color(0xFF1A1110)
val surfaceBrightDark = Color(0xFF423735)
val surfaceContainerLowestDark = Color(0xFF140C0B)
val surfaceContainerLowDark = Color(0xFF231918)
val surfaceContainerDark = Color(0xFF271D1C)
val surfaceContainerHighDark = Color(0xFF322826)
val surfaceContainerHighestDark = Color(0xFF3D3231)
